### ISSUE TITLE
Final .sh scripts got /W (windows line endings), terminal cann't run them

### ISSUE THREAD

**Issue by JuPlutonic** [nfisher1226/wmpipe#1]
When I run `sudo dos2unix -f NNN.sh` or opened it in Sublime-text and saved after chose `Menu-View\Line Endings\Unix` I got working scripts(pipemenus).
So, I got changed  line endings for all files in git-cloned directories. After test `make install` got all scripts working.

PS: what I did to get working WMPIPE on Ubuntu(Debian)
`sudo auto-apt run make PREFIX=/usr/local SYSCONFDIR=/etc`
`sudo auto-apt run checkinstall -D`
`sudo dpkg -i wmpipe_20170717-1_amd64.deb`
`sudo ln -s /usr/local/lib /opt/lib`

**Comment by nfisher1226** [comment]
Sorry, didn't see this. I will check through and fix any line termination issues. Probably a result of working in different environments.

Glad to hear it's working on Debian.

**Comment by nfisher1226** [comment]
Just did fresh checkouts on two machines, one linux and one freebsd, and I'm not able to reproduce this. All files have the proper LF line termination.
